"""fix user

Revision ID: 3580e652fcda
Revises: 9f7c0cd480e6
Create Date: 2023-11-23 04:12:32.378421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3580e652fcda'
down_revision: Union[str, None] = '9f7c0cd480e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_trial', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_trial')
    # ### end Alembic commands ###
