"""Fix User

Revision ID: 4a8b4959560d
Revises: 1b813ec49395
Create Date: 2023-10-24 06:31:07.385965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8b4959560d'
down_revision: Union[str, None] = '1b813ec49395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'created_at')
    # ### end Alembic commands ###
