"""fix

Revision ID: 6784f701297b
Revises: e7f4a4f49a34
Create Date: 2023-11-12 05:11:32.896721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6784f701297b'
down_revision: Union[str, None] = 'e7f4a4f49a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('paid', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('subscription_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription_date')
    op.drop_column('user', 'paid')
    # ### end Alembic commands ###
