"""Fix Message

Revision ID: 84b35b5ae9fc
Revises: e4745b4648d1
Create Date: 2023-11-01 05:47:14.575778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84b35b5ae9fc'
down_revision: Union[str, None] = 'e4745b4648d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('message', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('message', 'datetime')
    # ### end Alembic commands ###
