"""Add Message

Revision ID: e4745b4648d1
Revises: 4a8b4959560d
Create Date: 2023-11-01 04:31:50.856372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4745b4648d1'
down_revision: Union[str, None] = '4a8b4959560d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('POST', 'IMAGE', 'THEME', name='messagetypeenum'), nullable=True),
    sa.Column('chat', sa.Enum('POSTS', 'IMAGES', 'THEMES', name='chatenum'), nullable=True),
    sa.Column('sender', sa.Enum('USER', 'SYSTEM', name='senderenum'), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('post', 'project_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('project', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('post', 'project_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_table('message')
    # ### end Alembic commands ###
