"""Fix Message

Revision ID: ebfad1a5a3e5
Revises: 84b35b5ae9fc
Create Date: 2023-11-01 08:14:29.968839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfad1a5a3e5'
down_revision: Union[str, None] = '84b35b5ae9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
